# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = true

  config.vm.network :forwarded_port, guest: 8080, host: 80

  config.vm.synced_folder "src/", "/home/vagrant/app" , create:true
  config.vm.synced_folder "/usr/lib/jvm/java-8-oracle","/usr/lib/java/java-8-oracle", create:true
  config.vm.synced_folder "/usr/share/maven","/usr/share/maven",create:true
  config.vm.synced_folder "~/.m2/", "/home/vagrant/.m2" , create:true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "machine.sh",privileged:true
  config.vm.provision "shell", path: "config.sh",privileged:false

end
